import type { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/Navbar";
import { Header } from "../components/Header";
import { Stack } from "../components/Stack";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='bg-neutral-light-100 text-neutral-light-100 bg-light-pattern bg-repeat font-switzer overflow-x-hidden'>
        <Navbar />
        <Header />
        <Stack />
      </main>
    </>
  );
};

export default Home;
